name: Go Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.*'


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # - name: Get tag name
      #   id: get_tag
      #   run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'

      - run: go version

      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@v3.8.1
