name: golang

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: build go binary
        run: |
          BINARY_NAME="fivem-windows-amd64.exe"
          echo "Building binary: $BINARY_NAME"

          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w -H=windowsgui" -o "$BINARY_NAME" .
          echo "Built binary size: $(du -h "$BINARY_NAME")"

      - name: create github release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: fivem-windows-amd64.exe
          draft: false
          prerelease: false
