name: golang

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Get tag name
      #   id: get_tag
      #   run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      # - name: build
      #   run: GOOS=windows GOARCH=amd64 go build -v -ldflags "-H=windowsgui" -o fivem-windows-amd64.exe .

      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@v3.8.1

      - name: goreleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
